version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          key: haskell-dependencies-{{ checksum "stack.yaml" }}-{{ checksum "liquid-quarto.cabal" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Compile
          command: stack --no-terminal build --test --no-run-tests
      - run:
          name: Run tests
          command: stack test
      - save_cache:
          name: Cache Dependencies
          key: haskell-dependencies-{{ checksum "stack.yaml" }}-{{ checksum "liquid-quarto.cabal" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
